### ISSUE TITLE
SSO redirects wrongly to backend

### ISSUE THREAD

**Issue by IEEInfraPCE** [intuitem/ciso-assistant-community#1116]
**Describe the bug**
Setting up SSO according to your [documentation](https://intuitem.gitbook.io/ciso-assistant/features-highlight/sso/microsoft-entra-id). Then selecting "Login with SSO" on the login page redirects to http://backend:8000/api/iam/sso/redirect/ firstly showing an "insecure"-warning:
![image](https://github.com/user-attachments/assets/e3f2d939-29c5-4c5f-b0a8-e93dc76febe5)
Sending it anyways then leads to the suspected "name not found" error as backend is not a known domain:
![image](https://github.com/user-attachments/assets/b385e1db-9322-42ae-bf2e-2c473cacb2e9)

**To Reproduce**
1. Setup SSO with Manifest XML
2. Try to login

**Expected behavior**
Selecting "Login with SSO" should open Entra ID SAML login flow

**Screenshots**
![image](https://github.com/user-attachments/assets/7e29908b-af83-441e-a824-2cc352487dcf)

**Environment (please complete the following information):**
 - Device: Client Windows,  Server: Debian 12 (Ciso Assistant running in Docker)
 - Browser Edge 131.0.2903.70 (Official build) (64-bit)
 - Version v1.9.7

**Additional information**

Docker compose:
```
version: "3.9"

services:
  backend:
    container_name: backend
    image: ghcr.io/intuitem/ciso-assistant-community/backend:latest
    restart: always
    environment:
      - ALLOWED_HOSTS=backend
      - CISO_ASSISTANT_URL=https://<REDACTED>:8443
      - DJANGO_DEBUG=True
      - AUTH_TOKEN_TTL=7200
      - DEFAULT_FROM_EMAIL=<REDACTED>
      - EMAIL_HOST=<REDACTED>
      - EMAIL_PORT=25
    volumes:
      - ./db:/code/db

  frontend:
    container_name: frontend
    environment:
      - PUBLIC_BACKEND_API_URL=http://backend:8000/api
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host

    image: ghcr.io/intuitem/ciso-assistant-community/frontend:latest
    depends_on:
      - backend

  caddy:
    container_name: caddy
    image: caddy:2.7.6
    depends_on:
      - frontend
    restart: unless-stopped
    ports:
      - 8443:8443
    command:
      - caddy
      - reverse-proxy
      - --from
      - https:/<REDACTED>:8443
      - --to
      - frontend:3000
      - -i
    volumes:
      - ./caddy_data:/data
      - ./db:/data
```
