### ISSUE TITLE
Fetch failed, but I do not know where

### ISSUE THREAD

**Issue by wsw70** [intuitem/ciso-assistant-community#1358]
Fresh installation of ciso-assistant, on a docker reverse proxied by Caddy (the Caddy in the compose file is removed). I get an error 500 when going to the root of the site, the frontend logs show a `fetch` error.

I do not understand which call (actually - towards which endpoint) fails. The log is

```
TypeError: fetch failed
    at node:internal/deps/undici/undici:13484:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ensureCsrfToken (file:///app/build/server/chunks/hooks.server-DcGiXu3q.js:29:22)
    at async Object.handle (file:///app/build/server/chunks/hooks.server-DcGiXu3q.js:71:3)
    at async respond (file:///app/build/server/index.js:3489:22)
    at async Array.ssr (file:///app/build/handler.js:1284:3) {
  [cause]: AggregateError [ECONNREFUSED]: 
      at internalConnectMultiple (node:net:1139:18)
      at afterConnectMultiple (node:net:1712:7) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error] ]
  }
}
```

The docker compose file is

```yaml
volumes:
  grc-db:

networks:
  default:
    external: true
    name: caddy

services:
  grc-backend:
    container_name: grc-backend
    image: ghcr.io/intuitem/ciso-assistant-community/backend:latest
    restart: always
    environment:
      - ALLOWED_HOSTS=grc-frontend,grc-backend
      - CISO_ASSISTANT_URL=https://grc.security.example.com
      - DJANGO_DEBUG=True
      - AUTH_TOKEN_TTL=7200
    volumes:
      - grc-db:/code/db

  grc-frontend:
    container_name: grc-frontend
    environment:
      - PUBLIC_backend_API_URL=http://grc-backend:8000/api
      - PUBLIC_backend_API_EXPOSED_URL=https://grc.security.example.com/api
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
    image: ghcr.io/intuitem/ciso-assistant-community/frontend:latest
    depends_on:
      - grc-backend
    labels:
      caddy: grc.security.example.com
      caddy.tls: /config/certs/security.example.com.crt /config/certs/security.example.com.key
      caddy.@grc_frontend_root.path: /*
      caddy.0_reverse_proxy: "@grc_frontend_root grc-frontend:3000"
      caddy.@grc_backend_api.path: /api/*
      caddy.1_reverse_proxy: "@grc_backend_api grc-backend:8000"
```

My wild guess is that the problem is somewhere in `ALLOWED_HOSTS=grc-frontend,grc-backend`, I am not sure why the backend is referenced here (but maybe it calls itself) and frontend is the only one that is supposed to access.

Is there a way to further debug this?

---

Merci pour ce soft qui semble vraiment super! 🇫🇷
