### ISSUE TITLE
[traefik] No change on login after the initial deploy

### ISSUE THREAD

**Issue by IoannisKonstatinopoulos** [intuitem/ciso-assistant-community#1529]
**Describe the bug**
After installing the self-hosted version of CISO-assistant and creating the user for first login, we receive at first an error `{ detail: "Not Found" }` and then multiple times the another error  `SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON` . 
The above errors are triggered every time i try to login inside, and the login screen never changes. it's like i'm just getting the error.
Same error as can be viewed below, through inspect.

**To Reproduce**
1. Go to 'https://ciso.sample.dev/login?next=/'
2. Give login credentials as created - according to documentation.
2. Click on 'login'

**Expected behavior**
Login to service.

**Environment (please complete the following information):**
 - Device: laptop
 - OS: Fedora 41 Workstation
 - Browser: Firefox
 - Version: 135.0 (64-bit)

**Additional context**
Compose file used:
```
networks:
  traefik:
    external: true 

services:
  backend:
    image: ghcr.io/intuitem/ciso-assistant-community/backend:latest
    container_name: ciso-backend
    environment:
      - CISO_ASSISTANT_URL=https://ciso.sample.dev
      - ALLOWED_HOSTS=backend,localhost,ciso.sample.dev
      - DJANGO_DEBUG=True
      - AUTH_TOKEN_TTL=7200
    networks:
      - traefik
    volumes:
      - /opt/ciso/db:/code/db
    labels:
      traefik.enable: true
      traefik.http.routers.ciso-backend.rule: "Host(`ciso.sample.dev`) && Pathprefix(`/api/`)"
      traefik.http.routers.backend.entrypoints: websecure
      traefik.http.routers.backend.tls: true
      traefik.http.services.ciso-backend.loadbalancer.server.port: 8000
      traefik.http.middlewares.backendpathstrip.stripprefix.prefixes: /api
    restart: always
  frontend:
    image: ghcr.io/intuitem/ciso-assistant-community/frontend:latest
    container_name: ciso-frontend
    environment:
      - PUBLIC_BACKEND_API_URL=http://backend:8000/api/
      - PUBLIC_BACKEND_API_EXPOSED_URL=https://ciso.sample.dev/api/
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
    networks:
      - traefik
    depends_on:
      - backend
    labels:
      traefik.enable: true
      traefik.http.routers.ciso.rule: "Host(`ciso.sample.dev`) && Pathprefix(`/`)"
      traefik.http.routers.ciso.entrypoints: websecure
      traefik.http.routers.ciso.tls: true
      traefik.http.services.ciso.loadbalancer.server.port: 3000
      traefik.http.middlewares.cisopathstrip.stripprefix.prefixes: /
    restart: unless-stopped
```

[console-export-2025-2-21_16-54-21.txt](https://github.com/user-attachments/files/18908605/console-export-2025-2-21_16-54-21.txt)
[_ciso-frontend_logs.txt](https://github.com/user-attachments/files/18908604/_ciso-frontend_logs.txt)
