### ISSUE TITLE
403 when using CA new Helm as dependency

### ISSUE THREAD

**Issue by dr-lux** [intuitem/ciso-assistant-community#1631]
**Describe the bug**
I want to use CA as an helm dependency. When I build my Helm, I got this error:
```
InvalidSpecError: Unable to generate manifests in charts/ciso-assistant: rpc error: code = Unknown desc = `sh -c helm dependency build` failed exit status 1: Error: could not download oci://ghcr.io/intuitem/helm-charts/ce/ciso-assistant/ciso-assistant-release: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aintuitem%2Fhelm-charts%2Fce%2Fciso-assistant%2Fciso-assistant-release%3Apull&service=ghcr.io: 403 Forbidden
```
Seems we cannot retrieve the new helm chart.

**To Reproduce**
1. Use CA as dependency with Helm
```
apiVersion: v2
name: ciso-assistant
description: A Helm chart for CISO Assistant k8s's deployment
type: application
version: 0.1.0

dependencies:
  - name: ciso-assistant-release
    alias: cisoAssistant
    version: "0.3.0"
    repository: oci://ghcr.io/intuitem/helm-charts/ce/ciso-assistant
```

**Expected behavior**
Be able to use CA new Helm as dependency.

**Comment by p4block** [comment]
The correct format for oci subcharts is like this (omit chart name in repo)

```
apiVersion: v2
name: ciso-assistant
version: 1.0.0
dependencies:
- name: ciso-assistant
  version: 0.3.1
  repository: oci://ghcr.io/intuitem/helm-charts/ce
```
