### ISSUE TITLE
Port 443 not open in the docker compose yml when using config/make_config.py

### ISSUE THREAD

**Issue by defragm** [intuitem/ciso-assistant-community#1634]
**Describe the bug**

When using config/make_config.py and accepting that the ACME challenge can be use to setup the SSL certificate.
An error is thrown by caddy because let's encrypt is not able to contact the .well-known folder.
This bug can be fix by adding the 443 port to the caddy container when authorizing ACME challenge.
Here's the official documentation about the fact that the port need to be open.
https://letsencrypt.org/docs/challenge-types/#tls-alpn-01

**To Reproduce**

```
cd ~
git clone https://github.com/intuitem/ciso-assistant-community.git
python3 -m venv .venv
source .venv/bin/activate
cd ciso-assistant-community/config/
pip install -r requirements.txt
python3 make_config.py 
sudo ./docker-compose.sh 
deactivate
sudo docker compose -f docker-compose-custom.yml down
sudo docker compose -f docker-compose-custom.yml up
```
When using the wizard make_config.py select yes for the ACME challenge.
Once you arrived here you will see this line as compose is showing the logs.
You could find a way to see the logs earlier maybe by modifying the docker-compose.sh but I'm not an expert.

**Expected behavior**

I suggest adding this line when creating the custom docker compose yml.
```
caddy:
    container_name: caddy
    image: caddy:2.8.4
    environment:
      - CISO_ASSISTANT_URL=https://test.youcompany.com:8443
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 8443:8443
      - 443:443 #port for the ACME challenge
```

**Environment (please complete the following information):**
 - Device: VM
 - OS: debian 12
 - Browser no needed at this stage
 - Version 2.2.5
