### ISSUE TITLE
K8s resources and limits are ignored in the Helm Cart values.yaml

### ISSUE THREAD

**Issue by krupnikola** [intuitem/ciso-assistant-community#1684]
**Describe the bug**
No matter what I do in the values.yaml, the k8s resources/limits do not show up in the rendered kubernetes deployment when the applications get deployed.
This goes both for backend and frontend pods.

```
  # -- Resources for the backend
  resources:
  requests:
    cpu: 100m
    memory: 1024Mi
  limits:
    cpu: 256m
    memory: 2048Mi
```

**To Reproduce**
1. Uncomment the section with resources/limits for either backend or frontend in the values.yaml
2. Apply the helm 
3. Check if the limits/requests are visible in the resulting yaml in the cluster

In my case this is what I get:

```
...........................
    name: backend
    ports:
    - containerPort: 8000
      name: http
      protocol: TCP
    resources: {}
...............................
```

**Expected behavior**
Have the resources and limits set once they are uncommented/set in the values.yaml

**Screenshots**
Example for the memory usage:

<img width="904" alt="Image" src="https://github.com/user-attachments/assets/6564329d-e045-468f-99a3-54624e296df5" />

**Environment (please complete the following information):**
 - Google Cloud GKE
 - k8s version 1.30.x

**Additional context**
I suspect it is the indentation problem in the backend and frontend `deployment.yaml` templates. Haven't tested the rendering locally yet so it's just a suspicion for now.

**Comment by krupnikola** [comment]
I tested the local render with the changed deployment.yaml template and it indeed the indentation. This works as expected in my local template:

```
        - name: http
          containerPort: 8000
          protocol: TCP
        {{- if .Values.backend.resources }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
        {{- end }}
```
with 

```
  # -- Resources for the backend
  resources: 
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 256m
        memory: 1024Mi
```
rendering to 

```
        - name: http
          containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: 256m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 512Mi
```

and this ([current main](https://github.com/intuitem/ciso-assistant-community/blob/main/charts/ciso-assistant-next/templates/backend/deployment.yaml#L139-L141)) doesn't:

```
        {{- if .Values.backend.resources }}
        resources:
          {{ toYaml .Values.backend.resources | indent 10 }}
```
@Nathanael-Mtd is it ok if I make a PR for this ? (given that I see your name showing up as an author in these yamls)
