### ISSUE TITLE
Unable to deploy chart with postgresql because huey sqlite volume isn't created

### ISSUE THREAD

**Issue by p4block** [intuitem/ciso-assistant-community#1685]
**Describe the bug**
Huey needs persistence enabled to store its data in sqlite, however, the ciso-assistant-sqlite PVC is only created if databaseType is sqlite. 

**To Reproduce**
```
  backend:
    persistence:
      sqlite:
        enabled: true # for Huey
        
    config:
      databaseType: externalPgsql
```

**Expected behavior**
A PVC so huey can store its sqlite is created (or huey recycles the existing externalpostgres somehow)

**Additional context**
Chart right now seems un-installable in this kind of setup, but I could be missing something very obvious. It's Friday afterall.
