### ISSUE TITLE
matplotlib failed to create dir using helm charts

### ISSUE THREAD

**Issue by louisgls** [intuitem/ciso-assistant-community#1723]
**Describe the bug**

I'm using the helm chart version 0.3.3 and i have the following errors on backend container : 

```
mkdir -p failed for path /.config/matplotlib: [Errno 30] Read-only file system: '/.config'                                                                                                                                                  
Matplotlib created a temporary cache directory at /tmp/matplotlib-mlxbt7nk because there was an issue with the default path (/.config/matplotlib); it is highly recommended to set the MPLCONFIGDIR environment variable to a writable direc
tory, in particular to speed up the import of Matplotlib and to better support multiprocessing.                                                                                                                                             
Fontconfig error: No writable cache directories     
```

Applications works but it is slow without cache. I've set it up using `databaseType: pgsql` and disabled sqlite and localStorage:
```
    persistence:
      sqlite:
        enabled: false
      localStorage:
        enabled: false
```

I'm also running it in a restricted environnement so I have to apply securityContext ( I used the one commented in the chart) : 
```
    containerSecurityContext:
      seLinuxOptions: {}
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      privileged: false
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: "RuntimeDefault"
```
This is probably the reason why the folder can't be created.
Am I doing it right ?

**To Reproduce**
Helm chart 0.3.3 with security context and pgsql backend.

**Expected behavior**
I'm expecting the cache to work.
