### ISSUE TITLE
NPM fail on frontend image build

### ISSUE THREAD

**Issue by EvoXCX** [intuitem/ciso-assistant-community#227]
**Describe the bug**
Hello,

I tried to build image frontend image with Docker 26.0.0 and docker-compose 1.29.2 and I get this error
```shell
 > [ciso_frontend builder 6/8] RUN npm ci:
9.576 npm WARN ERESOLVE overriding peer dependency
9.580 npm WARN While resolving: @sveltejs/vite-plugin-svelte@2.5.3
9.580 npm WARN Found: vite@5.2.8
9.580 npm WARN node_modules/vite
9.580 npm WARN   dev vite@"^5.0.0" from the root project
9.581 npm WARN   10 more (@storybook/builder-vite, @storybook/svelte-vite, ...)
9.581 npm WARN
9.582 npm WARN Could not resolve dependency:
9.582 npm WARN peer vite@"^4.0.0" from @sveltejs/vite-plugin-svelte@2.5.3
9.582 npm WARN node_modules/@storybook/svelte-vite/node_modules/@sveltejs/vite-plugin-svelte
9.582 npm WARN   @sveltejs/vite-plugin-svelte@"^2.4.2" from @storybook/svelte-vite@7.6.17
9.582 npm WARN   node_modules/@storybook/svelte-vite
9.582 npm WARN   1 more (@sveltejs/vite-plugin-svelte-inspector)
9.583 npm WARN
9.583 npm WARN Conflicting peer dependency: vite@4.5.3
9.583 npm WARN node_modules/vite
9.584 npm WARN   peer vite@"^4.0.0" from @sveltejs/vite-plugin-svelte@2.5.3
9.584 npm WARN   node_modules/@storybook/svelte-vite/node_modules/@sveltejs/vite-plugin-svelte
9.584 npm WARN     @sveltejs/vite-plugin-svelte@"^2.4.2" from @storybook/svelte-vite@7.6.17
9.584 npm WARN     node_modules/@storybook/svelte-vite
9.585 npm WARN     1 more (@sveltejs/vite-plugin-svelte-inspector)
9.637 npm WARN ERESOLVE overriding peer dependency
9.639 npm WARN While resolving: @sveltejs/vite-plugin-svelte-inspector@1.0.4
9.639 npm WARN Found: vite@5.2.8
9.639 npm WARN node_modules/vite
9.640 npm WARN   dev vite@"^5.0.0" from the root project
9.641 npm WARN   10 more (@storybook/builder-vite, @storybook/svelte-vite, ...)
9.641 npm WARN
9.641 npm WARN Could not resolve dependency:
9.642 npm WARN peer vite@"^4.0.0" from @sveltejs/vite-plugin-svelte-inspector@1.0.4
9.643 npm WARN node_modules/@storybook/svelte-vite/node_modules/@sveltejs/vite-plugin-svelte/node_modules/@sveltejs/vite-plugin-svelte-inspector
9.643 npm WARN   @sveltejs/vite-plugin-svelte-inspector@"^1.0.4" from @sveltejs/vite-plugin-svelte@2.5.3
9.643 npm WARN
9.644 npm WARN Conflicting peer dependency: vite@4.5.3
9.644 npm WARN node_modules/vite
9.645 npm WARN   peer vite@"^4.0.0" from @sveltejs/vite-plugin-svelte-inspector@1.0.4
9.645 npm WARN   node_modules/@storybook/svelte-vite/node_modules/@sveltejs/vite-plugin-svelte/node_modules/@sveltejs/vite-plugin-svelte-inspector
9.646 npm WARN     @sveltejs/vite-plugin-svelte-inspector@"^1.0.4" from @sveltejs/vite-plugin-svelte@2.5.3
36.55 npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
38.12 npm WARN deprecated domexception@4.0.0: Use your platform's native DOMException instead
51.97
51.97 > frontend@0.0.1 postinstall
51.97 > paraglide-js compile --project ./project.inlang
51.97
53.03 ℹ [paraglide] Compiling inlang project at "./project.inlang".
53.12
53.12  WARN  Could not find repository root for path /app/project.inlang
53.12
64.40
64.40  WARN  The project has errors:
64.40
64.42
64.42  ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@latest/dist/index.js":
64.42
64.42 TypeError: fetch failed
64.42
64.42
64.42   TypeError: fetch failed
64.42   at resolveModules (node_modules/@inlang/paraglide-js/dist/index.js:21488:25)
64.42   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
64.42
64.42
64.42  ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-identical-pattern@latest/dist/index.js":
64.42
64.42 TypeError: fetch failed
64.42
64.42
64.42   TypeError: fetch failed
64.42   at resolveModules (node_modules/@inlang/paraglide-js/dist/index.js:21488:25)
64.42   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
64.42
64.42
64.42  ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@latest/dist/index.js":
64.42
64.42 TypeError: fetch failed
64.42
64.42
64.42   TypeError: fetch failed
64.42   at resolveModules (node_modules/@inlang/paraglide-js/dist/index.js:21488:25)
64.42   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
64.42
64.42
64.42  ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dist/index.js":
64.42
64.42 TypeError: fetch failed
64.42
64.42
64.42   TypeError: fetch failed
64.42   at resolveModules (node_modules/@inlang/paraglide-js/dist/index.js:21488:25)
64.42   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
64.42
64.42
64.42  ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-valid-js-identifier@latest/dist/index.js":
64.42
64.42 TypeError: fetch failed
64.42
64.42
64.42   TypeError: fetch failed
64.42   at resolveModules (node_modules/@inlang/paraglide-js/dist/index.js:21488:25)
64.42   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
64.42
64.42
64.42  ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@latest/dist/index.js":
64.42
64.42 TypeError: fetch failed
64.42
64.42
64.42   TypeError: fetch failed
64.42   at resolveModules (node_modules/@inlang/paraglide-js/dist/index.js:21488:25)
64.42   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
64.42
64.42
64.42  ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index.js":
64.42
64.42 TypeError: fetch failed
64.42
64.42
64.42   TypeError: fetch failed
64.42   at resolveModules (node_modules/@inlang/paraglide-js/dist/index.js:21488:25)
64.42   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
64.42
64.43
64.43  ERROR  No plugin provides a loadMessages() or saveMessages() function
64.43
64.43 In case no plugin threw an error, you likely forgot to add a plugin that handles the loading and saving of messages. Refer to the marketplace for available plugins https://inlang.com/marketplace.
64.43
64.43
64.43   In case no plugin threw an error, you likely forgot to add a plugin that handles the loading and saving of messages. Refer to the marketplace for available plugins https://inlang.com/marketplace.
64.43   at resolvePlugins (node_modules/@inlang/paraglide-js/dist/index.js:21454:24)
64.43   at resolveModules (node_modules/@inlang/paraglide-js/dist/index.js:21529:33)
64.43   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
64.43
64.47 npm ERR! code 1
64.47 npm ERR! path /app
64.47 npm ERR! command failed
64.48 npm ERR! command sh -c paraglide-js compile --project ./project.inlang
64.48
64.48 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-04-08T14_58_57_711Z-debug-0.log
------
failed to solve: process "/bin/sh -c npm ci" did not complete successfully: exit code: 1
```
I'm behind reverse proxy I don't think the problem come from that since packages are retrieved at the start.

Here is my docker-compose.yml
```yaml
services:
  ciso_backend:
    container_name: ciso_backend
    hostname: ciso_backend
    build: ./backend
    restart: always
    environment:
      - ALLOWED_HOSTS=backend
      - CISO_ASSISTANT_URL=https://ciso.domain.com
      - DJANGO_DEBUG=False
      # DB
      - POSTGRES_NAME=ciso
      - POSTGRES_USER=ciso_user
      - POSTGRES_PASSWORD=<password>
      - DB_HOST=ciso_db
      - DB_PORT=5432
      # Email
      - DEFAULT_FROM_EMAIL=ciso-assistant@domain.com
      - EMAIL_HOST=<smtp_host>
      - EMAIL_PORT=25

  ciso_frontend:
    container_name: ciso_frontend
    hostname: ciso_frontend
    build: ./frontend
    restart: always
    environment:
      - PUBLIC_BACKEND_API_URL=http://ciso_backend:8000/api
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
    depends_on:
      - ciso_backend
    ports:
      - 127.0.0.1:8001:8000

  ciso_db:
    image: docker.io/postgres:latest
    container_name: ciso_db
    hostname: ciso_db
    restart: always
    environment:
      - POSTGRES_USER=ciso_user
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_DB=ciso
    volumes:
      - /srv/cisoassistant/data:/var/lib/postgres/data
```

**To Reproduce**
1. Clone repo
2. Configure Dockerfile to use proxy
3. Adapt docker-compose.yml to my need
4. Build image before compose up

**Expected behavior**
A working image.

**Environment (please complete the following information):**
 - Device: Server (VM)
 - OS: Debian
 - Version 12.5

**Additional context**
I builded it successfully on Fedora 39 clean install, but can't import image to another docker node.

When I import it and launch, it say me that the image have no command.

**Comment by Mohamed-Hacene** [comment]
@EvoXCX, could you update your docker compose version and re-try it to be sure it's not related to it ?
Be sure to update `docker compose` and not `docker-compose`. The use of `docker-compose` is deprecated. see: [migrate to compose V2](https://docs.docker.com/compose/migrate/#how-do-i-switch-to-compose-v2)

**Comment by EvoXCX** [comment]
If is something I can do to help you to fix that ask me :)

**Comment by Mohamed-Hacene** [comment]
@EvoXCX thanks a lot ! It could be very useful to try without any proxy in your configuration. I've re-done the installation from scratch and I can't get the same error, the only thing I notice in common between the two issues is that you are behind a proxy.

**Comment by EvoXCX** [comment]
@Mohamed-Hacene Yeah proxy seem to be the problem but this is mandatory in my case, although it's weird because it's not a problem with installation (network) but with compiling, I'm investigating in the frontend container not fully builded to understand how it works exactly step by step.

**Comment by EvoXCX** [comment]
Let me know if you have a fix for this issue before me ;)

**Comment by Mohamed-Hacene** [comment]
Thanks for your help, I hope this isn't due to dependencies, as they are external to our application. 

We're also working on publishing our images to avoid this kind of problem. That way, you'll be able to compile them  with proxy or not without a hitch ;)

**Comment by EvoXCX** [comment]
This is a very good news !!!

When you think your image will be published ? I ask you that because this tool will help me to migrate to NIS2 in my context :)

I will update issue if I found something useful to solve this.

**Comment by Mohamed-Hacene** [comment]
As soon as possible, we first make sure they work on different configurations. 
Once again, thank you for your help and patience.

**Comment by EvoXCX** [comment]
Oups fail, I get login page but can't login, when I click on login button nothing happen.
Same on password reset page.

**Comment by EvoXCX** [comment]
Here is my new configuration
```yaml
services:
  backend:
    image: ghcr.io/intuitem/ciso-assistant-community/backend:latest
    container_name: ciso_backend
    hostname: backend
    restart: always
    environment:
      - ALLOWED_HOSTS=backend
      - CISO_ASSISTANT_URL=https://cisoassistant.domain.com
      - DJANGO_DEBUG=True
      # DB
      - POSTGRES_NAME=ciso
      - POSTGRES_USER=ciso_user
      - POSTGRES_PASSWORD=<password>
      - DB_HOST=ciso_db
      - DB_PORT=5432
      # Email
      - DEFAULT_FROM_EMAIL=ciso-assistant@domain.com
      - EMAIL_HOST=<smtp_server>
      - EMAIL_PORT=25

  frontend:
    image: ghcr.io/intuitem/ciso-assistant-community/frontend:latest
    container_name: ciso_frontend
    hostname: ciso_frontend
    #build: ./frontend
    restart: always
    environment:
      - PUBLIC_BACKEND_API_URL=http://backend:8000/api
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
    depends_on:
      - backend
    ports:
      - 127.0.0.1:3000:3000

  ciso_db:
    image: docker.io/postgres:latest
    container_name: ciso_db
    hostname: ciso_db
    restart: always
    environment:
      - POSTGRES_USER=ciso_user
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_DB=ciso
      - PGDATA=/var/lib/postgres/data
    volumes:
      - /srv/cisoassistant/data:/var/lib/postgres/data
```
