### ISSUE TITLE
Caddy with FQDN

### ISSUE THREAD

**Issue by Maker-Boot** [intuitem/ciso-assistant-community#261]
**Describe the bug**
I'm trying to configure a FQDN to access ciso assistant app but i have a connection refused.
(telnet: Unable to connect to remote host: Connection refused)

**To Reproduce**
Change docker-compose.yml :
  Change Backend VAR :  CISO_ASSISTANT_URL=https://ciso.local:8443
  Change Caddy url by : https://ciso.nikko.local
  Add -i to caddy config

**Expected behavior**
Web UI should appear and telnet should work on caddy exposed port.

**Environment (please complete the following information):**
- Ubuntu 22.04 (jammy)
- Docker version 26

Docker config :
```
version: "3.9"

services:
  backend:
    container_name: backend
    image: ghcr.io/intuitem/ciso-assistant-community/backend:latest
    restart: always
    environment:
      - ALLOWED_HOSTS=backend
      - CISO_ASSISTANT_URL=https://ciso.local:8443
      - DJANGO_DEBUG=True
    volumes:
      - ./db:/code/db

  frontend:
    container_name: frontend
    environment:
      - PUBLIC_BACKEND_API_URL=http://backend:8000/api
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
    image: ghcr.io/intuitem/ciso-assistant-community/frontend:latest
    depends_on:
      - backend

  caddy:
    container_name: caddy
    image: caddy:2.7.6
    restart: unless-stopped
    ports:
      - 8443:8443
    command:
      - caddy
      - reverse-proxy
      - --from
      - https://ciso.local
      - --to
      - frontend:3000
      - -i
    volumes:
      - ./db:/data
```

Docker ps
CONTAINER ID   IMAGE                                                       COMMAND                  CREATED          STATUS         PORTS                                                                           NAMES
ff53791ab1e2   ghcr.io/intuitem/ciso-assistant-community/frontend:latest   "docker-entrypoint.s…"   6 minutes ago    Up 6 minutes   3000/tcp                                                                        frontend
900b088d8a34   ghcr.io/intuitem/ciso-assistant-community/backend:latest    "bash startup.sh"        16 minutes ago   Up 6 minutes   8000/tcp                                                                        backend
aa75029cb72a   caddy:2.7.6                                                 "caddy reverse-proxy…"   16 minutes ago   Up 6 minutes   80/tcp, 443/tcp, 2019/tcp, 443/udp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp   caddy

netstat -tunlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      30581/docker-proxy
tcp6       0      0 :::8443                 :::*                    LISTEN      30588/docker-proxy

Caddy log
```
{"level":"warn","ts":1713191624.283862,"logger":"admin","msg":"admin endpoint disabled"}
{"level":"info","ts":1713191624.2841592,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000394c80"}
{"level":"info","ts":1713191624.2843564,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"proxy","https_port":443}
{"level":"info","ts":1713191624.2843742,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"proxy"}
{"level":"warn","ts":1713191624.30753,"logger":"pki.ca.local","msg":"installing root certificate (you might be prompted for password)","path":"storage:pki/authorities/local/root.crt"}
{"level":"info","ts":1713191624.3078496,"msg":"warning: \"certutil\" is not available, install \"certutil\" with \"apt install libnss3-tools\" or \"yum install nss-tools\" and try again"}
{"level":"info","ts":1713191624.3078616,"msg":"define JAVA_HOME environment variable to use the Java trust"}
{"level":"info","ts":1713191624.3451345,"msg":"certificate installed properly in linux trusts"}
{"level":"info","ts":1713191624.3463805,"logger":"http","msg":"enabling HTTP/3 listener","addr":":443"}
{"level":"info","ts":1713191624.3465269,"msg":"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details."}
{"level":"info","ts":1713191624.3468025,"logger":"http.log","msg":"server running","name":"proxy","protocols":["h1","h2","h3"]}
{"level":"info","ts":1713191624.346855,"logger":"http.log","msg":"server running","name":"remaining_auto_https_redirects","protocols":["h1","h2","h3"]}
{"level":"info","ts":1713191624.346866,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["ciso.local"]}
{"level":"warn","ts":1713191624.3494506,"logger":"tls","msg":"stapling OCSP","error":"no OCSP stapling for [*.local localhost]: no OCSP server specified in certificate","identifiers":["*.local","localhost"]}
Caddy proxying https://ciso.local -> frontend:3000
{"level":"warn","ts":1713191624.35001,"logger":"tls","msg":"storage cleaning happened too recently; skipping for now","storage":"FileStorage:/data/caddy","instance":"c578598c-b558-467f-872b-c669785d0463","try_again":1713278024.350008,"try_again_in":86399.999999608}
{"level":"info","ts":1713191624.3500931,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1713192207.6556282,"msg":"shutting down apps, then terminating","signal":"SIGTERM"}
{"level":"warn","ts":1713192207.6557248,"msg":"exiting; byeee!! 👋","signal":"SIGTERM"}
{"level":"info","ts":1713192207.6559622,"logger":"http","msg":"servers shutting down with eternal grace period"}
{"level":"info","ts":1713192207.6564848,"msg":"shutdown complete","signal":"SIGTERM","exit_code":0}
{"level":"warn","ts":1713192212.1010666,"logger":"admin","msg":"admin endpoint disabled"}
{"level":"info","ts":1713192212.101299,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00048aa00"}
{"level":"info","ts":1713192212.1019592,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"proxy","https_port":443}
{"level":"info","ts":1713192212.1019783,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"proxy"}
{"level":"info","ts":1713192212.1285663,"logger":"pki.ca.local","msg":"root certificate is already trusted by system","path":"storage:pki/authorities/local/root.crt"}
{"level":"info","ts":1713192212.128943,"logger":"http.log","msg":"server running","name":"remaining_auto_https_redirects","protocols":["h1","h2","h3"]}
{"level":"info","ts":1713192212.1289856,"logger":"http","msg":"enabling HTTP/3 listener","addr":":443"}
{"level":"info","ts":1713192212.1291244,"msg":"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details."}
{"level":"info","ts":1713192212.1293335,"logger":"http.log","msg":"server running","name":"proxy","protocols":["h1","h2","h3"]}
{"level":"info","ts":1713192212.1293406,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["ciso.local"]}
{"level":"warn","ts":1713192212.1305852,"logger":"tls","msg":"stapling OCSP","error":"no OCSP stapling for [*.local localhost]: no OCSP server specified in certificate","identifiers":["*.local","localhost"]}
Caddy proxying https://ciso.local -> frontend:3000
{"level":"warn","ts":1713192212.1331465,"logger":"tls","msg":"storage cleaning happened too recently; skipping for now","storage":"FileStorage:/data/caddy","instance":"c578598c-b558-467f-872b-c669785d0463","try_again":1713278612.1331441,"try_again_in":86399.999999586}
{"level":"info","ts":1713192212.133242,"logger":"tls","msg":"finished cleaning storage units"}
```
