### ISSUE TITLE
Critical risk matrix 4x4 request

### ISSUE THREAD

**Issue by grov** [intuitem/ciso-assistant-community#337]
**Request statement**
My Risk framework is based on a Risk Matrix 4x4.
Is it possible to add a 4x4 risk matrix in the library ? 

With the following legend example : 
- High
- Significant
- Medium
- Low

Thank you very much !

**Comment by ab-smith** [comment]
Hey, sure, you can get some inspiration from the libraries folder in [the libraries](https://github.com/intuitem/ciso-assistant-community/tree/main/backend/library/libraries) folder and definitely have that.
You can also share a screenshot and we'll pick it up later next week.

**Comment by grov** [comment]
Thank you it was easier than expected !
Here is the code if needed : 

```
urn: urn:intuitem:risk:library:critical_risk_matrix_4x4
locale: en
ref_id: critical_4x4
name: Critical risk matrix 4x4
description: Critical risk matrix 4x4
version: 1
provider: intuitem
packager: intuitem
objects:
  risk_matrix:
    - urn: urn:intuitem:risk:matrix:critical_risk_matrix_4x4
      ref_id: critical_4x4
      name: critical 4x4
      description: critical risk matrix 4x4
      probability:
        - abbreviation: UL
          name: Unlikely
          description: Very unfrequent event
        - abbreviation: P
          name: Possible
          description: Unfrequent event
        - abbreviation: L
          name: Likely
          description: Frequent
        - abbreviation: H
          name: High
          description: Frequent or permanent
      impact:
        - abbreviation: MN
          name: Minor
          description: Minor impact
        - abbreviation: MD
          name: Moderate
          description: Moderate impact
        - abbreviation: S
          name: Significant
          description: Significant impact
        - abbreviation: MJ
          name: Major
          description: Major impact
      risk:
        - abbreviation: MN
          name: Minor
          description: negligible risk
          hexcolor: "#BBF7D0"
        - abbreviation: MD
          name: Moderate
          description: risk requiring mitigation within 2 years
          hexcolor: "#FEF08A"
        - abbreviation: S
          name: Significant
          description: risk requiring mitigation within 6 months
          hexcolor: "#FBBF24"
        - abbreviation: MJ
          name: Major
          description: unacceptable risk
          hexcolor: "#F87171"
      grid:
        - - 0
          - 0
          - 0
          - 1
        - - 0
          - 1
          - 1
          - 2
        - - 1
          - 1
          - 2
          - 3
        - - 1
          - 2
          - 3
          - 3
```
