### ISSUE TITLE
Add possibilty to import vulnerability as vuln, and not as threats

### ISSUE THREAD

**Issue by EvoXCX** [intuitem/ciso-assistant-community#426]
**Problem statement**
Hello,
I'm adding ISO/27005 in my forked repo and will open a PR when finished it, but my problem is ISO/27005 have threats and vulnerabilities only and no controls measures, but in yaml files documentation there is no category to specify vulns and same in CISO GUI, it will be very nice if you add this functionality.

**Example**
```yml
...
  threats:
    - urn: urn:intuitem:risk:threat:iso27005-threats:cf05
      ref_id: CF05
      name: Breach of personnel availability
      description: ""
  
  vulns:
    - urn: urn:intuitem:risk:threat:iso27005-threats:h01
      ref_id: H01
      category: <Hardware, Software, Network, Personnel, Site, Organization>
      name: Insufficient maintenance/faulty installation of storage media
      description: "Short desc"
```

Maybe you can add vulns reference to have better filtering and categorization on Risk Assessment or Audit.
