### ISSUE TITLE
Private self signed certificate from our own PKI

### ISSUE THREAD

**Issue by izav** [intuitem/ciso-assistant-community#468]
**Problem statement**
What is the process to use our own self signed certificates from our internal PKI instead of the caddy default one or -i option
Best

**Comment by EvoXCX** [comment]
Hello @izav,
You can use Nginx reverse proxy by example:
```bash
server {
        listen 443 ssl;
        listen [::]:443 ssl;

        ssl_certificate /etc/ssl/ciso/ciso.domain.com.crt;
        ssl_certificate_key /etc/ssl/ciso/ciso.domain.com.pem;
        ssl_session_timeout 1d;
        ssl_session_cache shared:MozSSL:10m;
        ssl_session_tickets off;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
        ssl_prefer_server_ciphers off;

        add_header Strict-Transport-Security "max-age=63072000" always;

        server_name ciso.domain.com;
        location / {
                proxy_pass      http://127.0.0.1:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}
```

Modify your docker-compose.yml frontend and backend according to this:
```yml
services:
  backend:
    image: ghcr.io/intuitem/ciso-assistant-community/backend:latest
    container_name: ciso_backend
    hostname: backend
    restart: always
    environment:
      - ALLOWED_HOSTS=backend
      - CISO_ASSISTANT_URL=https://ciso.domain.com

  frontend:
    image: ghcr.io/intuitem/ciso-assistant-community/frontend:latest
    container_name: ciso_frontend
    hostname: frontend
    restart: always
    environment:
      - PUBLIC_BACKEND_API_URL=http://backend:8000/api
      - ORIGIN=https://ciso.domain.com
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
    depends_on:
      - backend
    ports:
      - 127.0.0.1:3000:3000
```

> [!NOTE]
> Define correctly ORIGIN, ALLOWED_HOSTS, CISO_ASSISTANT_URL accordingly to your configuration

**Comment by ab-smith** [comment]
@eric-intuitem good point to improve in our documentation

**Comment by izav** [comment]
ok solved with this within docker-compose.yml :

     - ORIGIN=https://ciso.domain.com:8443

**Comment by izav** [comment]
Final setup

```
version: "3.9"

volumes:
  certificats:
    external: true

services:
  backend:
    container_name: ciso_backend
    hostname: backend
    image: ghcr.io/intuitem/ciso-assistant-community/backend:latest
    restart: always
    environment:
      - ALLOWED_HOSTS=backend
      - CISO_ASSISTANT_URL=https://ciso.domain.com:8443
      - DJANGO_DEBUG=True
    volumes:
      - ./db:/code/db

  frontend:
    container_name: ciso_frontend
    hostname: frontend
    image: ghcr.io/intuitem/ciso-assistant-community/frontend:latest
    restart: always
    environment:
      - PUBLIC_BACKEND_API_URL=http://backend:8000/api
      - ORIGIN=https://ciso.domain.com:8443
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
    depends_on:
      - backend
    ports:
      - 127.0.0.1:3000:3000

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8443:8443
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:rw
      - certificats:/etc/ssl/certs/:ro
```
      
where in ./nginx/ there is a default.conf


```
      server {
        listen 8443 ssl;
        listen [::]:8443 ssl;

        ssl_certificate /etc/ssl/certs/ciso.domain.com.cer;
        ssl_certificate_key /etc/ssl/certs/ciso.domain.com.key;
        ssl_session_timeout 1d;
        ssl_session_cache shared:MozSSL:10m;
        ssl_session_tickets off;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
        ssl_prefer_server_ciphers off;

        add_header Strict-Transport-Security "max-age=63072000" always;

        server_name ciso.domain.com;
        location / {
                proxy_pass      http://frontend:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}
```
