### ISSUE TITLE
Wrong SSO redirect URL

### ISSUE THREAD

**Issue by ArchdukeNavaron** [intuitem/ciso-assistant-community#681]
**Describe the bug**

I am trying to deploy ciso-assistant but I am struggeling with getting SSO set up.
Our setup is, that we have a nginx ingress proxy in our Kubernetes Cluster. The traffic is then forwarded to the frontend.
Afterwards, the frontend should directly communicate with the backend without the need of our ingress proxy.

Frontend configuration:

```yaml
env:
  - name: HOST_HEADER
    value: x-forwarded-host
  - name: PROTOCOL_HEADER
    value: x-forwarded-proto
  - name: PUBLIC_BACKEND_API_URL
    value: http://ciso-assistant-backend:8000/api
  - name: PUBLIC_BACKEND_API_EXPOSED_URL
    value: https://ciso-assistant.example.com/api
```

Backend configuration:

```yaml
env:
  - name: ALLOWED_HOSTS
    value: ciso-assistant.example.com,ciso-assistant-backend
  - name: CISO_ASSISTANT_URL
    value: https://ciso-assistant.example.com
  - name: DB_HOST
    ...
```

When I try to login with SAML, the redirect URL is without HTTPS `http://ciso-assistant.example.com/api/accounts/saml/0/acs/`
I think this happens because the frontend and backend communicate with each other without TLS but I am not sure.

Note: I can get it working, when i play all traffic via the ingress proxy. But this has a noticeable performance impact. And because the response times are not great from the beginning, it makes it almost unusable.

**Expected behavior**

Frontend and backend can communicate with each other without TLS (our connection underneath is already encrytpted between containers. So there is no need for additional TLS.

Users still get correct redirect URL and can login with SSO.
